### ISSUE TITLE
[Dev] Multiple dependencies for CI missing

### ISSUE THREAD

**Issue by DanielYang59** [materialsproject/pymatgen#3684]
Multiple external dependencies are missing from test setup, including:
- [x] `mcsqs`: not planned (https://github.com/materialsproject/pymatgen/issues/3684#issuecomment-1988998112)
- [x] `icet`: not planned (https://github.com/materialsproject/pymatgen/issues/3684#issuecomment-1987687507)
- [x] `emmet`: not planned (https://github.com/materialsproject/pymatgen/issues/3684#issuecomment-1987690470)
- [x] `Open Babel`: added in #3729
- [x] `enum_lib`: Added for Ubuntu only in #3729
- [x] `gulp`: not planned (libgfortran3 not supported by Ubuntu20 afterwards)
- [ ] `graphviz`
- [ ] `critic2`: https://aoterodelaroza.github.io/critic2/installation/
- [ ] `OBAlign`
- [ ] `vampire`
- [ ] `x_trans`
- [ ] `boltztrap2`
- [ ] `zeo`

Is this intended or should we fix it?

**Comment by janosh** [comment]
i believe missing `icet` was deliberate as @esoteric-ephemera [added it only to `requirements-optional.txt`](https://github.com/materialsproject/pymatgen/pull/3593/files#diff-d52eaab4a615f02e5a1b6e6dd9e17be0c5f0519bcdb433cd28c45705b569da45R14) which is not used in CI.

though i could see how that is confusing which is why i've advocated for removing the requirements files in the past. @shyuep prefers to keep. i fwiw, i think the `atomate2` approach is better of having a [`strict` optional deps section in pyproject.toml](https://github.com/materialsproject/atomate2/blob/9f6438150d63706d6f9bf9b63f143932be27b82b/pyproject.toml#L72)

**Comment by janosh** [comment]
`emmet` is purposefully not installed as it comes with a host of transitive deps.

as for the others, i think it would be good to install and test their respective `pymatgen` integrations in CI

**Comment by esoteric-ephemera** [comment]
> i believe missing icet was deliberate as @esoteric-ephemera [added it only to requirements-optional.txt](https://github.com/materialsproject/pymatgen/pull/3593/files#diff-d52eaab4a615f02e5a1b6e6dd9e17be0c5f0519bcdb433cd28c45705b569da45R14) which is not used in CI.

That was deliberate. The same logic applies to `mcsqs`  and a few other packages here. Tho that tends to mean that tests for these aren't actively maintained since CI never runs them (could suddenly have broken tests / interfaces if breaking changes are made in a dependency)

**Comment by DanielYang59** [comment]
> Tho that tends to mean that tests for these aren't actively maintained since CI never runs them (could suddenly have broken tests / interfaces if breaking changes are made in a dependency)

But I assume it's still beneficial to keep the tests alive for robustness? (Issues are more likely to slip in if tests are skipped)

Anyway, I would try to install some of these dependencies locally and see if any broken tests show up, and I would keep you updated.

**Comment by janosh** [comment]
@DanielYang59 feel free to install some of the missing packages in CI as well to activate those tests. ideally, we don't want to be blocked by upstream packages in our development ([see e.g. tblite](https://github.com/tblite/tblite/pull/122#issuecomment-1990610135)) but if a package is actively maintained and easy to install, it makes sense to add itin CI

**Comment by DanielYang59** [comment]
A very late update, I ran tests for `mcsqs` locally and looks like it's not aging too badly and [only the timeout exception test is failing](https://github.com/materialsproject/pymatgen/pull/4209#discussion_r1864154532)

I haven't investigated on the design of `mcsqs_caller` but it seems to raise three different timeout errors. I would just replace the error message in #4209 as both points to `mcsqs` timeout, let me know if I'm misunderstanding anything

https://github.com/materialsproject/pymatgen/blob/31f1e1fb8cc1bb517d59ea8e484965bb641c42a0/src/pymatgen/command_line/mcsqs_caller.py#L136-L169

https://github.com/materialsproject/pymatgen/blob/31f1e1fb8cc1bb517d59ea8e484965bb641c42a0/src/pymatgen/command_line/mcsqs_caller.py#L147
https://github.com/materialsproject/pymatgen/blob/31f1e1fb8cc1bb517d59ea8e484965bb641c42a0/src/pymatgen/command_line/mcsqs_caller.py#L157-L159
https://github.com/materialsproject/pymatgen/blob/31f1e1fb8cc1bb517d59ea8e484965bb641c42a0/src/pymatgen/command_line/mcsqs_caller.py#L169
